version: "3.9"

x-common-labels: &common-labels
  labels:
    project-name: "rational-ui"
    comment: ""
    domain: "staging-rational"
    environment: "staging"
    git: "***REMOVED***"
    branch: "development"
    maintainer: "***REMOVED***"
    devops-engineer: "***REMOVED***"

x-args: &args
  args:
    NODE_MAJOR: 18
    APP_ROOT: /app
    NG_CLI_VERSION: 15.0.5
    ENVIRONMENT: staging
    APP_HOSTNAME: staging-rational

x-syslog-driver: &syslog-driver
  logging:
    driver: syslog
    options:
      syslog-address: "${RSYSLOG_URL}"
      tag: "{{.Name}}/{{.ID}}"

x-jsonlog-driver: &jsonlog-driver
  logging:
    driver: "json-file"

x-env: &envs
  environment:
    - TZ=Asia/Krasnoyarsk
    - APP_ROOT=/app

x-common: &common
  restart: unless-stopped
  stdin_open: true
  tty: true

x-ui: &app
  image: ${CI_REGISTRY_IMAGE}/rational-ui--staging--app
  build:
    <<: *common-labels
    <<: *args
    context: .
    dockerfile: .docker/Dockerfiles/app.Dockerfile

x-frontend: &frontend
  <<: *common-labels
  <<: *syslog-driver
  <<: *envs
  <<: *app
  <<: *common

services:
  rational-ui--staging--app:
    <<: *frontend
    container_name: rational-ui--staging--app
#    mac_address: ***REMOVED***
#    networks:
#      macvlan:
#        ipv4_address: ***REMOVED***
    deploy:
      resources:
        reservations:
          memory: 64mb
        limits:
          memory: 128mb

networks:
  macvlan:
    external:
      name: server-network
